version: "3.2"
services:

  dev-db:
    image: postgres:10.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forum
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend/
    restart: always
    environment:
      DB_HOST: dev-db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      DB_NAME: forum
    ports:
      - "28000:8000"
    depends_on:
      - dev-db
    volumes:
      - ./backend:/app

  frontend:
      build: ./frontend
      command: ["npm", "start"]
      ports:
        - "23000:3000"
      volumes:
        - ./frontend:/app/frontend
        - node-modules:/app/frontend/node_modules

volumes:
  node-modules:
