version: "3.2"
services:

  app:
    build: .
    restart: always
    environment:
      DB_HOST: dev-db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      DB_NAME: forum
    ports:
      - "8000:8000"
    depends_on:
      - dev-db
    volumes:
      - ./:/app

  dev-db:
    image: postgres:10.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forum
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
